inversify/inversify-express-example

.gitignore, BasicExample/bootstrap.ts, BasicExample/controller/home.ts, BasicExample/controller/user.ts, BasicExample/service/user.ts, BasicExample/test/controller/home.spec.ts, BasicExample/test/controller/user.spec.ts, BasicExample/test/service/user.spec.ts, README.md, package.json, tsconfig.json, tslint.json, typings.json
Added a really basic example on how to use inversify with express.
Also added some project initial stuff.
@remojansen , @codyjs would be nice if you can take a look :)
=> Added a basic exmaple

package.json
Like title says
Maybe we can add a script that runs all unit tests. Then we could add travis and greenkeeper
=> Updated inversify-dts dep

package.json
Everything seems to be fine :+1:
=> Updating versions

.travis.yml, README.md, appveyor.yml
As promised, added travis and appveyor as ci :)
=> added travis and appveyor as ci

.travis.yml, appveyor.yml
I can reproduce this error when I turn off MongoDB on my local machine. So I added MongoDB as a service on travis and on appveyor.
=> fixing issue #280

Basic/bootstrap.ts, Basic/constant/tags.ts, Basic/constant/types.ts, Basic/controller/home.ts, Basic/controller/user.ts, Basic/service/user.ts, BindingDecorators/README.md, BindingDecorators/bootstrap.ts, BindingDecorators/constant/tags.ts, BindingDecorators/constant/types.ts, BindingDecorators/controller/home.ts, BindingDecorators/controller/user.ts, BindingDecorators/ioc/ioc.ts, BindingDecorators/ioc/loader.ts, BindingDecorators/models/user.ts, BindingDecorators/service/user.ts, BindingDecorators/test/controller/home.spec.ts, BindingDecorators/test/controller/user.spec.ts, BindingDecorators/test/utils/mongodb/client.spec.ts, BindingDecorators/utils/mongodb/client.ts, BindingDecorators/utils/mongodb/connection.ts, MongoDB/bootstrap.ts, MongoDB/constant/tags.ts, MongoDB/constant/types.ts, MongoDB/controller/home.ts, MongoDB/controller/user.ts, MongoDB/service/user.ts, package.json, typings.json
Added an example that uses `inversify-binding-decorators` and constants to already available examples.
=> Added inversify-binding-decorators example

package.json
Fixes dependency issues 
These PR can be closed with this: #17, #14, #13, #12
=> fixes dependency issues

MiddlewareInjection/README.md, MiddlewareInjection/controller.ts, MiddlewareInjection/main.ts, README.md, package.json
Made a small example of the solution to this [stack overflow question](http://stackoverflow.com/questions/39632122/inversifyjs-inject-middleware-into-controller/39672904), as it seems to be a pretty common use case.
It's pretty simplistic so I didn't bother with any unit tests.
=> Add Middleware Injection Example

package.json
Closes #88
https://greenkeeper.io/
=> chore(package): update @types/mongodb to version 2.1.35

Basic/bootstrap.ts, Basic/test/controller/home.spec.ts, BindingDecorators/bootstrap.ts, BindingDecorators/ioc/ioc.ts, MiddlewareInjection/controller.ts, MiddlewareInjection/main.ts, MongoDB/bootstrap.ts, package.json, tsconfig.json
=> updating dependencies and inversify

package.json
Closes #88
https://greenkeeper.io/
=> chore(package): update @types/mongodb to version 2.1.39

package.json
Closes #88
https://greenkeeper.io/
=> chore(package): update @types/mongodb to version 2.1.41

package.json
Closes #88
https://greenkeeper.io/
=> chore(package): update @types/mongodb to version 2.1.43

BindingDecorators/ioc/loader.ts, BindingDecorators/utils/mongodb/client.ts, package.json
1. Fix imports on loader.ts
2. Use provider annotation on mongo db client.ts
=> Errors on bindingdecorators example

appveyor.yml
When running builds on appveyor we need to clean the node_modules folder after each build as that will not tamper the build process
That will fix old dependancies residing inside the node_modules
I've added a flag to specify a no cache build for Appveyor.
=> Appveyor - Cleaning up cache before each build

.gitignore, .travis.yml, Basic/bootstrap.ts, Basic/controller/home.ts, Basic/controller/user.ts, BindingDecorators/controller/home.ts, BindingDecorators/controller/user.ts, BindingDecorators/utils/mongodb/client.ts, MiddlewareInjection/controller.ts, MiddlewareInjection/main.ts, MongoDB/bootstrap.ts, MongoDB/controller/home.ts, MongoDB/controller/user.ts, package.json, tsconfig.json
Updated dependencies
N/A
Updated dependencies
CI
=> Updated dependencies

package.json
=> chore(package): update @types/chai to version 4.0.5

package.json
=> chore(package): update @types/mongodb to version 2.2.16

Basic/bootstrap.ts, Basic/controller/home.ts, Basic/controller/user.ts, BindingDecorators/controller/home.ts, BindingDecorators/controller/user.ts, MiddlewareInjection/controller.ts, MiddlewareInjection/main.ts, MongoDB/bootstrap.ts, MongoDB/controller/home.ts, MongoDB/controller/user.ts, package.json
Upgraded inversify-express-utils@5.0.0-beta.1
=> Upgraded inversify-express-utils@5.0.0-beta.1

package.json
=> chore(package): update @types/chai to version 4.0.7

BindingDecorators/test/utils/mongodb/client.spec.ts, BindingDecorators/utils/mongodb/client.ts, BindingDecorators/utils/mongodb/connection.ts, MongoDB/test/utils/mongodb/client.spec.ts, MongoDB/utils/mongodb/client.ts, MongoDB/utils/mongodb/connection.ts, package.json
Replaces https://github.com/inversify/inversify-express-example/pull/299
=> Upgrade mongodb@3.0.2

package.json
=> fix(package): update inversify-express-utils to version 6.0.0

package.json
=> chore(package): update @types/mongodb to version 3.0.15

package.json
=> fix(package): update inversify to version 5.0.1

package.json
=> fix(package): update pg to version 7.6.1

package.json
=> fix(package): update pg to version 7.7.1

package.json
=> chore(package): update @types/mongodb to version 3.1.17

package.json
=> fix(package): update typeorm to version 0.2.16

package.json
=> fix(package): update pg to version 7.9.0
